import type { Project, Document, User, Clause, ClauseCategory } from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@accordify.com',
    role: 'Administrator',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    department: 'Legal',
    status: 'active',
    lastLogin: '2025-12-10T10:30:00Z',
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@accordify.com',
    role: 'Collaborator',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    department: 'Procurement',
    status: 'active',
    lastLogin: '2025-12-10T09:15:00Z',
    createdAt: '2024-02-20T09:00:00Z',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael.chen@accordify.com',
    role: 'Legal Reviewer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    department: 'Legal',
    status: 'active',
    lastLogin: '2025-12-09T16:45:00Z',
    createdAt: '2024-03-10T09:00:00Z',
  },
  {
    id: '4',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@accordify.com',
    role: 'Finance Approver',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    department: 'Finance',
    status: 'active',
    lastLogin: '2025-12-10T08:00:00Z',
    createdAt: '2024-04-05T09:00:00Z',
  },
  {
    id: '5',
    name: 'David Kim',
    email: 'david.kim@accordify.com',
    role: 'Approver',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    department: 'Operations',
    status: 'active',
    lastLogin: '2025-12-09T17:30:00Z',
    createdAt: '2024-05-12T09:00:00Z',
  },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Enterprise Software License Agreement',
    type: 'Contract',
    status: 'Active',
    priority: 'High',
    description: 'Master software license agreement for enterprise clients with comprehensive terms covering usage rights, support, and maintenance.',
    dueDate: '2025-12-31T23:59:59Z',
    progress: 75,
    owner: mockUsers[0],
    team: [
      { user: mockUsers[0], role: 'Owner', addedAt: '2025-11-01T09:00:00Z' },
      { user: mockUsers[2], role: 'Reviewer', addedAt: '2025-11-01T09:00:00Z' },
      { user: mockUsers[3], role: 'Reviewer', addedAt: '2025-11-01T09:00:00Z' },
    ],
    documentCount: 8,
    tags: ['Enterprise', 'Software', 'High-Value'],
    createdAt: '2025-11-01T09:00:00Z',
    updatedAt: '2025-12-09T15:30:00Z',
  },
  {
    id: '2',
    name: 'Q1 2026 IT Equipment RFP',
    type: 'RFP',
    status: 'In Review',
    priority: 'Critical',
    description: 'Request for Proposal for IT equipment procurement including servers, workstations, and networking equipment.',
    dueDate: '2026-01-15T23:59:59Z',
    progress: 60,
    owner: mockUsers[1],
    team: [
      { user: mockUsers[1], role: 'Owner', addedAt: '2025-11-15T09:00:00Z' },
      { user: mockUsers[4], role: 'Reviewer', addedAt: '2025-11-15T09:00:00Z' },
    ],
    documentCount: 5,
    tags: ['Procurement', 'IT', 'Q1'],
    createdAt: '2025-11-15T09:00:00Z',
    updatedAt: '2025-12-10T11:20:00Z',
  },
  {
    id: '3',
    name: 'Cloud Services Provider Agreement',
    type: 'Agreement',
    status: 'Draft',
    priority: 'Medium',
    description: 'Service level agreement with cloud infrastructure provider covering uptime guarantees, data security, and support terms.',
    dueDate: '2026-02-28T23:59:59Z',
    progress: 30,
    owner: mockUsers[0],
    team: [
      { user: mockUsers[0], role: 'Owner', addedAt: '2025-11-20T09:00:00Z' },
      { user: mockUsers[1], role: 'Editor', addedAt: '2025-11-20T09:00:00Z' },
    ],
    documentCount: 3,
    tags: ['Cloud', 'Infrastructure', 'SLA'],
    createdAt: '2025-11-20T09:00:00Z',
    updatedAt: '2025-12-08T14:00:00Z',
  },
  {
    id: '4',
    name: 'Marketing Services Solicitation',
    type: 'Solicitation',
    status: 'Active',
    priority: 'Medium',
    description: 'Solicitation for digital marketing and brand management services for 2026 fiscal year.',
    dueDate: '2026-01-30T23:59:59Z',
    progress: 45,
    owner: mockUsers[1],
    team: [
      { user: mockUsers[1], role: 'Owner', addedAt: '2025-11-25T09:00:00Z' },
    ],
    documentCount: 4,
    tags: ['Marketing', 'Services'],
    createdAt: '2025-11-25T09:00:00Z',
    updatedAt: '2025-12-07T10:15:00Z',
  },
  {
    id: '5',
    name: 'Facility Maintenance Contract Renewal',
    type: 'Contract',
    status: 'Completed',
    priority: 'Low',
    description: 'Annual renewal of facility maintenance and janitorial services contract.',
    dueDate: '2025-12-01T23:59:59Z',
    progress: 100,
    owner: mockUsers[4],
    team: [
      { user: mockUsers[4], role: 'Owner', addedAt: '2025-10-01T09:00:00Z' },
      { user: mockUsers[0], role: 'Reviewer', addedAt: '2025-10-01T09:00:00Z' },
    ],
    documentCount: 6,
    tags: ['Facilities', 'Renewal'],
    createdAt: '2025-10-01T09:00:00Z',
    updatedAt: '2025-12-01T16:00:00Z',
  },
  {
    id: '6',
    name: 'Data Privacy Compliance Review',
    type: 'Other',
    status: 'In Review',
    priority: 'High',
    description: 'Comprehensive review of all contracts for GDPR and CCPA compliance requirements.',
    dueDate: '2025-12-20T23:59:59Z',
    progress: 55,
    owner: mockUsers[2],
    team: [
      { user: mockUsers[2], role: 'Owner', addedAt: '2025-11-10T09:00:00Z' },
      { user: mockUsers[0], role: 'Reviewer', addedAt: '2025-11-10T09:00:00Z' },
    ],
    documentCount: 12,
    tags: ['Compliance', 'Privacy', 'Legal'],
    createdAt: '2025-11-10T09:00:00Z',
    updatedAt: '2025-12-09T13:45:00Z',
  },
];

// Mock Documents
export const mockDocuments: Document[] = [
  {
    id: '1',
    name: 'Master_Software_License_v3.2.pdf',
    type: 'Contract',
    status: 'Active',
    projectId: '1',
    projectName: 'Enterprise Software License Agreement',
    fileSize: 2458624,
    mimeType: 'application/pdf',
    uploadedBy: mockUsers[0],
    uploadedAt: '2025-11-05T10:30:00Z',
    updatedAt: '2025-12-08T14:20:00Z',
    aiAnalysisStatus: 'Complete',
    tags: ['Master Agreement', 'Executed'],
    version: 3,
  },
  {
    id: '2',
    name: 'Software_License_Addendum_2025.docx',
    type: 'Amendment',
    status: 'In Review',
    projectId: '1',
    projectName: 'Enterprise Software License Agreement',
    fileSize: 156789,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: mockUsers[2],
    uploadedAt: '2025-12-01T09:15:00Z',
    updatedAt: '2025-12-09T11:30:00Z',
    aiAnalysisStatus: 'Complete',
    tags: ['Addendum', 'Review'],
    version: 2,
  },
  {
    id: '3',
    name: 'IT_Equipment_RFP_Draft.pdf',
    type: 'RFP',
    status: 'Draft',
    projectId: '2',
    projectName: 'Q1 2026 IT Equipment RFP',
    fileSize: 3567890,
    mimeType: 'application/pdf',
    uploadedBy: mockUsers[1],
    uploadedAt: '2025-11-20T08:00:00Z',
    updatedAt: '2025-12-10T10:00:00Z',
    aiAnalysisStatus: 'Analyzing',
    tags: ['RFP', 'Draft'],
    version: 1,
  },
  {
    id: '4',
    name: 'Technical_Specifications.docx',
    type: 'Other',
    status: 'Active',
    projectId: '2',
    projectName: 'Q1 2026 IT Equipment RFP',
    fileSize: 445678,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: mockUsers[1],
    uploadedAt: '2025-11-22T14:30:00Z',
    updatedAt: '2025-12-05T09:20:00Z',
    aiAnalysisStatus: 'Complete',
    tags: ['Technical', 'Specifications'],
    version: 2,
  },
  {
    id: '5',
    name: 'Cloud_SLA_Template.pdf',
    type: 'Agreement',
    status: 'Draft',
    projectId: '3',
    projectName: 'Cloud Services Provider Agreement',
    fileSize: 1234567,
    mimeType: 'application/pdf',
    uploadedBy: mockUsers[0],
    uploadedAt: '2025-11-25T11:00:00Z',
    updatedAt: '2025-12-08T15:45:00Z',
    aiAnalysisStatus: 'Complete',
    tags: ['SLA', 'Template'],
    version: 1,
  },
  {
    id: '6',
    name: 'Marketing_Services_SOW.docx',
    type: 'Solicitation',
    status: 'Active',
    projectId: '4',
    projectName: 'Marketing Services Solicitation',
    fileSize: 678901,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: mockUsers[1],
    uploadedAt: '2025-11-28T10:00:00Z',
    updatedAt: '2025-12-07T13:15:00Z',
    aiAnalysisStatus: 'Complete',
    tags: ['SOW', 'Marketing'],
    version: 1,
  },
];

// Mock Clause Categories
export const mockClauseCategories: ClauseCategory[] = [
  { id: '1', name: 'Confidentiality', description: 'Non-disclosure and confidentiality clauses', clauseCount: 15 },
  { id: '2', name: 'Indemnification', description: 'Indemnification and liability clauses', clauseCount: 12 },
  { id: '3', name: 'Termination', description: 'Contract termination clauses', clauseCount: 18 },
  { id: '4', name: 'Payment Terms', description: 'Payment schedules and terms', clauseCount: 10 },
  { id: '5', name: 'Intellectual Property', description: 'IP rights and ownership clauses', clauseCount: 14 },
  { id: '6', name: 'Limitation of Liability', description: 'Liability limitation clauses', clauseCount: 8 },
  { id: '7', name: 'Force Majeure', description: 'Force majeure and act of God clauses', clauseCount: 6 },
  { id: '8', name: 'Dispute Resolution', description: 'Arbitration and dispute resolution clauses', clauseCount: 9 },
];

// Mock Clauses
export const mockClauses: Clause[] = [
  {
    id: '1',
    title: 'Standard Non-Disclosure Agreement',
    content: 'The Receiving Party agrees to hold in confidence and not disclose to any third parties any Confidential Information received from the Disclosing Party, except as expressly permitted herein. Confidential Information includes all technical and business information disclosed by the Disclosing Party.',
    category: 'Confidentiality',
    tags: ['NDA', 'Standard', 'Confidentiality'],
    createdBy: mockUsers[2],
    createdAt: '2024-06-15T09:00:00Z',
    usageCount: 24,
    lastUsed: '2025-12-05T14:30:00Z',
  },
  {
    id: '2',
    title: 'Mutual Indemnification Clause',
    content: 'Each Party agrees to indemnify, defend, and hold harmless the other Party from and against any and all claims, damages, losses, and expenses arising out of or resulting from the indemnifying Party\'s breach of this Agreement or negligent acts or omissions.',
    category: 'Indemnification',
    tags: ['Indemnification', 'Mutual', 'Liability'],
    createdBy: mockUsers[2],
    createdAt: '2024-07-20T09:00:00Z',
    usageCount: 18,
    lastUsed: '2025-12-08T10:15:00Z',
  },
  {
    id: '3',
    title: 'Termination for Convenience',
    content: 'Either Party may terminate this Agreement for convenience upon thirty (30) days written notice to the other Party. Upon termination, all rights and obligations shall cease except those that by their nature are intended to survive termination.',
    category: 'Termination',
    tags: ['Termination', 'Convenience', 'Notice'],
    createdBy: mockUsers[0],
    createdAt: '2024-08-10T09:00:00Z',
    usageCount: 32,
    lastUsed: '2025-12-09T16:20:00Z',
  },
  {
    id: '4',
    title: 'Net 30 Payment Terms',
    content: 'Payment shall be due within thirty (30) days from the date of invoice. All payments shall be made in United States Dollars via wire transfer or check. Late payments shall accrue interest at a rate of 1.5% per month or the maximum rate permitted by law, whichever is less.',
    category: 'Payment Terms',
    tags: ['Payment', 'Net 30', 'Invoice'],
    createdBy: mockUsers[3],
    createdAt: '2024-09-05T09:00:00Z',
    usageCount: 45,
    lastUsed: '2025-12-10T09:00:00Z',
  },
  {
    id: '5',
    title: 'Intellectual Property Ownership',
    content: 'All intellectual property rights in and to the deliverables created under this Agreement shall vest exclusively in the Client. The Contractor agrees to execute any documents necessary to perfect such rights and hereby assigns all such rights to the Client.',
    category: 'Intellectual Property',
    tags: ['IP', 'Ownership', 'Assignment'],
    createdBy: mockUsers[2],
    createdAt: '2024-10-12T09:00:00Z',
    usageCount: 21,
    lastUsed: '2025-12-06T11:45:00Z',
  },
];

export const getMockUser = (id: string): User | undefined => {
  return mockUsers.find(user => user.id === id);
};

export const getMockProject = (id: string): Project | undefined => {
  return mockProjects.find(project => project.id === id);
};

export const getMockDocument = (id: string): Document | undefined => {
  return mockDocuments.find(doc => doc.id === id);
};

export const getMockClause = (id: string): Clause | undefined => {
  return mockClauses.find(clause => clause.id === id);
};